version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "stylus*"
      - dependency-name: "eslint*"
      - dependency-name: "@vue/*"
      - dependency-name: "vue/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
